name: cloudtype-fastapi
app: python@3.9
options:
  ports: 8000
  start: uvicorn main:app --host=0.0.0.0 --port=8000
context:
  git:
    url: https://github.com/LeeHongSoek/cloudtype_fastapi.git
    branch: main
  preset: python-fastapi
