name: "Python Run Snp_PriceSqlite.py"
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  python-job:
    name: "Python job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10.6'
      - name: Install dependencies
        run: pip install -r pipInstalls.txt
      - name: Run python script
        run: python SnP500/Snp_PriceSqlite.py
